### ISSUE TITLE
Upsert dora api support

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neon-js#700]
This issue covers the replacement of existing Neoscan endpoints and addition and use of the dora api.  The scope of the issue encompasses both the Neo Legacy and N3 releases to accommodate Neoscan EoL.

**Comment by snowypowers** [comment]
For Neo Legacy, it is definitely possible. 

For N3, I have removed the old interface because the requirements has drastically changed since. For readonly purposes, I think having a dora & neo-node adapter is do-able. However, for forming transactions, invokefunction rpc is used plenty so dora at the current state might not be suitable.

**Comment by snowypowers** [comment]
I took a look at the api docs. I did not see immediately where can I retrieve the list of UTXOs available for an address (neoscan's getBalance). It says its deprecated so I assume I cannot use those. Any ideas?

**Comment by lllwvlvwlll** [comment]
@hal0x2328 do we provide this anywhere in the new api?

**Comment by hal0x2328** [comment]
That endpoint is deprecated in the sense that Neo2 is deprecated so this particular endpoint won't be part of the N3 API going forward. But it could still be dropped in to the Neo2 parts of neon-js as a replacement for Neoscan, it won't be replaced by anything else in the future.

**Comment by snowypowers** [comment]
Can I get a backend check? https://dora.coz.io/address/neo2/testnet/ALq7AWrhAueN6mJNqk6FHJjnsEoPRytLdW shows correctly but all the deprecated methods like https://dora.coz.io/api/v1/neo2/testnet/get_balance/ALq7AWrhAueN6mJNqk6FHJjnsEoPRytLdW shows nothing

**Comment by hal0x2328** [comment]
Try again now, there was a bug on the testnet side that I just fixed.

**Comment by snowypowers** [comment]
You can click on the link in my comment, its still not working. I will work with mainnet for now but its not very nice to put someone's mainnet address as a test vector xD

**Comment by hal0x2328** [comment]
I had to restart the endpoint router after the change, the external link works now

**Comment by lllwvlvwlll** [comment]
@snowypowers how difficult would it be to remove neoscan/dora from the integral functions of the sdk entirely?  My understanding is that our plugins on the nodes should be able to provision the necessary information.  

We could then split out the dora api support into a dedicated package which helps separate concerns.

**Comment by snowypowers** [comment]
Are you speaking for N3? I have removed the support for external providers in N3 for now since the workflow has changed drastically, increasing the reliance of the invokescript/invokefunction RPC endpoints.

For Neo Legacy, it is always possible to put it apart though I am not sure of the benefits of that work if there is not going to be much iteration.

**Comment by snowypowers** [comment]
neo2 support is published @ v4.9.0
